### PR TITLE
Fixes #7 by switching to positional arguments

### LINKED ISSUE #7: Symfony 3.4 support
First - just wanted to say thanks for this bundle. We've been using it in production for a very long time now and it's great.

We're looking to upgrade to Symfony 3.4 and we're getting this error:

Invalid service "markdownify": the value of argument "linksAfterEachParagraph" of method "Markdownify\ConverterExtra::__construct()" must be null, an instance of Symfony\Component\DependencyInjection\Reference or an instance of Symfony\Component\DependencyInjection\Definition, integer given.

I believe we need to make a change to the service config:

      linksAfterEachParagraph: '%markdownify.link_position%'

becomes:

      $linksAfterEachParagraph: '%markdownify.link_position%'

or:

      0: '%markdownify.link_position%'

(Where 0 is the argument position)

### PR DESCRIPTION
**Pull request by edhgoose**

### CODE REVIEW

**Comment by pkruithof** [comment]
Can you add Symfony 3.4 to the Travis build matrix?

**Comment by edhgoose** [comment]
Certainly. I also note the after_script here https://github.com/pkruithof/markdownify-bundle/blob/5a7ec63ef451b4ba6e46556856ab3b9c5fe28496/.travis.yml#L38 - do I need to include a check for 3.4 here as well?

**Comment by pkruithof** [comment]
You can change it to `3.4`. The reason it's there is so that only 1 build uploads coverage to Scrutinizer. The build fails by the way 😉

**Comment by edhgoose** [comment]
Hey @pkruithof, I've fixed those tests. And I've made a couple changes to the travis.yml as it kept crashing with out of memory. Think it's good to go now.

**Comment by pkruithof** [comment]
Thanks. 

FYI: I was hesitating to add support for Symfony 4 as well, but to be honest I think it's easier to just register the service yourself. So I'm leaning towards deprecating this bundle.

**Pull request merged**
